# Generated by Django 5.2.5 on 2025-08-18 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="patient",
            unique_together={("doctor", "name")},
        ),
    ]
